#!/usr/bin/env python3
"""Visual Tuner — a dependency-free local CSS tuning workspace.

Run: python3 visual_tuner.py --dir /absolute/path/to/site
Or:  python3 visual_tuner.py --url http://127.0.0.1:5173
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
import posixpath
import sys
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from http import HTTPStatus
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from pathlib import Path


TOOL_DIR = Path(__file__).resolve().parent
WEB_DIR = TOOL_DIR / "web"
WORKSPACES_DIR = TOOL_DIR / "workspaces"
BRIDGE_PATH = WEB_DIR / "bridge.js"


def safe_workspace_name(source: str) -> str:
    readable = Path(urllib.parse.urlparse(source).path).name or "site"
    readable = "".join(char.lower() if char.isalnum() else "-" for char in readable).strip("-") or "site"
    return f"{readable}-{hashlib.sha1(source.encode()).hexdigest()[:8]}"


def fresh_state(source: str) -> dict:
    return {
        "version": 1,
        "source": source,
        "enabled": True,
        "rules": {"desktop": {}, "tablet": {}, "mobile": {}},
    }


class TunerServer(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(self, address: tuple[str, int], handler: type[BaseHTTPRequestHandler], source_dir: Path | None, source_url: str | None):
        super().__init__(address, handler)
        self.source_dir = source_dir
        self.source_url = source_url.rstrip("/") if source_url else None
        source = str(source_dir.resolve()) if source_dir else self.source_url or "site"
        self.workspace_dir = WORKSPACES_DIR / safe_workspace_name(source)
        self.workspace_dir.mkdir(parents=True, exist_ok=True)
        self.state_file = self.workspace_dir / "changes.json"
        self.css_file = self.workspace_dir / "overrides.css"
        self.source_label = source
        self.state = self.load_state()

    def load_state(self) -> dict:
        if self.state_file.exists():
            try:
                state = json.loads(self.state_file.read_text(encoding="utf-8"))
                if state.get("version") == 1 and isinstance(state.get("rules"), dict):
                    state.setdefault("source", self.source_label)
                    state.setdefault("enabled", True)
                    for breakpoint in ("desktop", "tablet", "mobile"):
                        state["rules"].setdefault(breakpoint, {})
                    return state
            except (OSError, json.JSONDecodeError):
                pass
        return fresh_state(self.source_label)

    def save_state(self, state: dict) -> None:
        state["version"] = 1
        state["source"] = self.source_label
        for breakpoint in ("desktop", "tablet", "mobile"):
            state.setdefault("rules", {}).setdefault(breakpoint, {})
        self.state = state
        self.state_file.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        self.css_file.write_text(css_from_state(state), encoding="utf-8")


def css_from_state(state: dict) -> str:
    rules = state.get("rules", {})
    sections: list[str] = ["/* Generated by Visual Tuner. Integrate these overrides into the site's stylesheet when ready. */"]
    for breakpoint, query in (("desktop", None), ("tablet", "@media (max-width: 1023px)"), ("mobile", "@media (max-width: 767px)")):
        chunks: list[str] = []
        for selector, props in rules.get(breakpoint, {}).items():
            if not selector or not isinstance(props, dict):
                continue
            declarations = [f"  {name}: {value};" for name, value in props.items() if value not in (None, "")]
            if declarations:
                chunks.append(f"{selector} {{\n" + "\n".join(declarations) + "\n}")
        if chunks:
            block = "\n\n".join(chunks)
            sections.append(block if query is None else f"{query} {{\n" + indent(block) + "\n}")
    return "\n\n".join(sections) + "\n"


def indent(text: str) -> str:
    return "\n".join("  " + line for line in text.splitlines())


class Handler(BaseHTTPRequestHandler):
    server: TunerServer

    def log_message(self, fmt: str, *args: object) -> None:
        # Keep launch output useful rather than logging every image request.
        if self.path.startswith("/__vt__/"):
            sys.stderr.write("[Visual Tuner] " + (fmt % args) + "\n")

    def do_GET(self) -> None:
        parsed = urllib.parse.urlsplit(self.path)
        if parsed.path in ("/__vt__", "/__vt__/"):
            return self.serve_file(WEB_DIR / "index.html", "text/html; charset=utf-8")
        if parsed.path == "/__vt__/app.js":
            return self.serve_file(WEB_DIR / "app.js", "application/javascript; charset=utf-8")
        if parsed.path == "/__vt__/app.css":
            return self.serve_file(WEB_DIR / "app.css", "text/css; charset=utf-8")
        if parsed.path == "/__vt__/bridge.js":
            return self.serve_file(BRIDGE_PATH, "application/javascript; charset=utf-8")
        if parsed.path == "/__vt__/overrides.css":
            return self.send_text(css_from_state(self.server.state), "text/css; charset=utf-8")
        if parsed.path == "/__vt__/api/state":
            return self.send_json({"state": self.server.state, "source": self.server.source_label, "workspace": str(self.server.workspace_dir)})
        if parsed.path == "/__vt__/api/export":
            return self.send_text(css_from_state(self.server.state), "text/css; charset=utf-8", attachment="visual-tuner-overrides.css")
        return self.serve_target(parsed)

    def do_POST(self) -> None:
        if urllib.parse.urlsplit(self.path).path != "/__vt__/api/state":
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length).decode("utf-8"))
            state = payload.get("state")
            if not isinstance(state, dict):
                raise ValueError("Missing state")
            self.server.save_state(state)
            self.send_json({"ok": True, "workspace": str(self.server.workspace_dir), "css": str(self.server.css_file)})
        except (ValueError, UnicodeDecodeError, json.JSONDecodeError, OSError) as exc:
            self.send_json({"ok": False, "error": str(exc)}, status=HTTPStatus.BAD_REQUEST)

    def serve_file(self, path: Path, content_type: str) -> None:
        try:
            self.send_text(path.read_text(encoding="utf-8"), content_type)
        except OSError:
            self.send_error(HTTPStatus.NOT_FOUND)

    def send_text(self, text: str, content_type: str, status: HTTPStatus = HTTPStatus.OK, attachment: str | None = None) -> None:
        body = text.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        if attachment:
            self.send_header("Content-Disposition", f'attachment; filename="{attachment}"')
        self.end_headers()
        self.wfile.write(body)

    def send_json(self, data: dict, status: HTTPStatus = HTTPStatus.OK) -> None:
        self.send_text(json.dumps(data, ensure_ascii=False), "application/json; charset=utf-8", status)

    def serve_target(self, parsed: urllib.parse.SplitResult) -> None:
        if self.server.source_dir:
            self.serve_local_target(parsed)
        else:
            self.serve_proxied_target(parsed)

    def serve_local_target(self, parsed: urllib.parse.SplitResult) -> None:
        relative = urllib.parse.unquote(parsed.path).lstrip("/") or "index.html"
        normalized = posixpath.normpath(relative)
        if normalized.startswith("../") or normalized == "..":
            self.send_error(HTTPStatus.FORBIDDEN)
            return
        candidate = (self.server.source_dir / normalized).resolve()
        try:
            candidate.relative_to(self.server.source_dir)
        except ValueError:
            self.send_error(HTTPStatus.FORBIDDEN)
            return
        if candidate.is_dir():
            candidate = candidate / "index.html"
        if not candidate.is_file():
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        try:
            body = candidate.read_bytes()
        except OSError:
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        content_type = mimetypes.guess_type(str(candidate))[0] or "application/octet-stream"
        self.send_target_response(body, content_type)

    def serve_proxied_target(self, parsed: urllib.parse.SplitResult) -> None:
        upstream = self.server.source_url + self.path
        request = urllib.request.Request(upstream, headers={"Accept-Encoding": "identity", "User-Agent": "Visual-Tuner/1.0"})
        try:
            with urllib.request.urlopen(request, timeout=12) as response:
                body = response.read()
                content_type = response.headers.get_content_type()
                charset = response.headers.get_content_charset() or "utf-8"
                if content_type == "text/html":
                    try:
                        body = inject_bridge(body.decode(charset)).encode("utf-8")
                    except UnicodeDecodeError:
                        pass
                self.send_response(response.status)
                self.send_header("Content-Type", response.headers.get("Content-Type", content_type))
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "no-store")
                self.end_headers()
                self.wfile.write(body)
        except urllib.error.HTTPError as exc:
            self.send_error(exc.code, f"Target returned {exc.reason}")
        except (urllib.error.URLError, TimeoutError) as exc:
            self.send_error(HTTPStatus.BAD_GATEWAY, f"Cannot reach target: {exc.reason if hasattr(exc, 'reason') else exc}")

    def send_target_response(self, body: bytes, content_type: str) -> None:
        if content_type.startswith("text/html"):
            try:
                body = inject_bridge(body.decode("utf-8")).encode("utf-8")
                content_type = "text/html; charset=utf-8"
            except UnicodeDecodeError:
                pass
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)


def inject_bridge(html: str) -> str:
    snippet = '<link id="visual-tuner-overrides" rel="stylesheet" href="/__vt__/overrides.css"><script src="/__vt__/bridge.js"></script>'
    if "</head>" in html.lower():
        index = html.lower().rfind("</head>")
        return html[:index] + snippet + html[index:]
    return snippet + html


def main() -> None:
    parser = argparse.ArgumentParser(description="Open a local site in Visual Tuner.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--dir", type=Path, help="Folder containing index.html and site assets")
    source.add_argument("--url", help="Already-running local site URL, for example http://127.0.0.1:5173")
    parser.add_argument("--port", type=int, default=4178, help="Visual Tuner port (default: 4178)")
    parser.add_argument("--no-open", action="store_true", help="Do not open the browser automatically")
    args = parser.parse_args()

    target_dir = args.dir.resolve() if args.dir else None
    if target_dir and not (target_dir / "index.html").is_file():
        parser.error(f"{target_dir} does not contain index.html")
    if args.url:
        parsed = urllib.parse.urlparse(args.url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            parser.error("--url must be a full http:// or https:// URL")

    WORKSPACES_DIR.mkdir(exist_ok=True)
    server = TunerServer(("127.0.0.1", args.port), Handler, target_dir, args.url)
    app_url = f"http://127.0.0.1:{args.port}/__vt__/"
    print("\nVisual Tuner is ready.")
    print("Open:", app_url)
    print("Workspace:", server.workspace_dir)
    print("Press Ctrl+C to stop.\n")
    if not args.no_open:
        webbrowser.open(app_url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nVisual Tuner stopped.")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
