const BREAKPOINTS = { desktop: { width: 1440, label: 'Desktop' }, tablet: { width: 834, label: 'Tablet' }, mobile: { width: 390, label: 'Mobile' } };
const CONTROL_PROPS = ['font-size','line-height','letter-spacing','font-weight','text-align','white-space','width','height','max-width','margin','padding','gap','color','opacity','border-radius','z-index','object-fit','object-position','position','top','left','display','flex-direction','justify-content','align-items','grid-template-columns'];

const el = {
  frame: document.querySelector('#site-frame'), viewport: document.querySelector('#viewport-frame'), name: document.querySelector('#selection-name'), selector: document.querySelector('#selector'), parent: document.querySelector('#select-parent'), empty: document.querySelector('#empty-state'), controls: document.querySelector('#controls'), status: document.querySelector('#status'), viewportLabel: document.querySelector('#viewport-label'), undo: document.querySelector('#undo'), redo: document.querySelector('#redo'), save: document.querySelector('#save'), compare: document.querySelector('#compare-toggle'), resetProp: document.querySelector('#reset-property'), resetElement: document.querySelector('#reset-element'), preview: document.querySelector('#css-preview'), count: document.querySelector('#change-count'), copy: document.querySelector('#copy-css'),
  textEditor: document.querySelector('#text-editor'), textEditorHint: document.querySelector('#text-editor-hint'), duplicateBtn: document.querySelector('#duplicate-element'), deleteBtn: document.querySelector('#delete-element')
};
let state = null;
let resolveStateReady;
const stateReady = new Promise(resolve => { resolveStateReady = resolve; });
let activeBreakpoint = 'desktop';
let selection = null;
let selectedProperty = null;
let history = [];
let historyIndex = -1;
let applying = false;

const clone = value => JSON.parse(JSON.stringify(value));
const rules = () => state.rules[activeBreakpoint];
const selectorRules = () => selection ? (rules()[selection.selector] || {}) : {};

function cssFromState(data = state) {
  const sections = ['/* Generated by Visual Tuner. Integrate these overrides into the site stylesheet when ready. */'];
  [['desktop', null], ['tablet', '@media (max-width: 1023px)'], ['mobile', '@media (max-width: 767px)']].forEach(([breakpoint, media]) => {
    const blocks = Object.entries(data.rules[breakpoint] || {}).map(([selector, props]) => {
      const declarations = Object.entries(props).filter(([, value]) => value !== '' && value !== null).map(([property, value]) => `  ${property}: ${value};`);
      return declarations.length ? `${selector} {\n${declarations.join('\n')}\n}` : '';
    }).filter(Boolean);
    if (blocks.length) sections.push(media ? `${media} {\n${blocks.join('\n\n').split('\n').map(line => '  ' + line).join('\n')}\n}` : blocks.join('\n\n'));
  });
  return sections.join('\n\n') + '\n';
}

function totalChanges() { return Object.values(state.rules).reduce((sum, selectors) => sum + Object.values(selectors).reduce((count, props) => count + Object.keys(props).length, 0), 0); }
function postToFrame(payload) { el.frame.contentWindow?.postMessage({ visualTuner: true, ...payload }, window.location.origin); }
function applyOverrides() { postToFrame({ type:'set-overrides', css:cssFromState(), enabled:state.enabled }); postToFrame({ type:'rescan' }); }

function updateChrome() {
  const count = totalChanges();
  el.preview.textContent = count ? cssFromState() : '/* No overrides yet */';
  el.count.textContent = count;
  el.undo.disabled = historyIndex <= 0;
  el.redo.disabled = historyIndex >= history.length - 1;
  el.resetProp.disabled = !selection || !selectedProperty || !(selectedProperty in selectorRules());
  el.compare.setAttribute('aria-pressed', String(state.enabled));
  el.status.textContent = state.enabled ? (count ? `${count} override${count === 1 ? '' : 's'} active` : 'Click any element to inspect it') : 'Original — overrides are hidden';
}

function recordHistory() {
  if (applying) return;
  history = history.slice(0, historyIndex + 1);
  history.push({ rules: clone(state.rules), content: clone(state.content) });
  historyIndex = history.length - 1;
  updateChrome();
}
function restoreHistory(index) {
  if (index < 0 || index >= history.length) return;
  const previousContent = JSON.stringify(state.content);
  applying = true;
  state.rules = clone(history[index].rules);
  state.content = clone(history[index].content);
  historyIndex = index;
  applying = false;
  renderControls();
  // Duplicate/delete are DOM mutations, not CSS — the only reliable way to
  // undo/redo them is to reload the frame and replay state.content fresh.
  if (JSON.stringify(state.content) !== previousContent) el.frame.contentWindow.location.reload();
  else applyOverrides();
  updateChrome();
}

function recordContentOp(op) {
  if (op.op === 'text') {
    const idx = state.content.findIndex(existing => existing.op === 'text' && existing.selector === op.selector);
    if (idx >= 0) state.content[idx] = op; else state.content.push(op);
  } else {
    state.content.push(op);
  }
  recordHistory();
}
function duplicateElement() {
  if (!selection) return;
  const op = { op:'duplicate', selector: selection.selector, newId: 'vt-node-' + Math.random().toString(36).slice(2, 9) };
  postToFrame({ type:'content-op', op });
  recordContentOp(op);
}
function deleteElement() {
  if (!selection) return;
  postToFrame({ type:'content-op', op:{ op:'delete', selector: selection.selector } });
  recordContentOp({ op:'delete', selector: selection.selector });
  selection = null; selectedProperty = null;
  el.controls.classList.add('hidden'); el.empty.classList.remove('hidden');
  el.name.textContent = 'Nothing selected'; el.selector.textContent = 'Click a site element'; el.parent.disabled = true;
  updateChrome();
}

function numericValue(raw) {
  const match = String(raw || '').trim().match(/^(-?[\d.]+)([a-z%]*)$/i);
  return match ? { value: Number(match[1]), unit: match[2] } : { value: 0, unit: '' };
}
function rgbToHex(value) {
  if (/^#[\da-f]{6}$/i.test(value)) return value;
  const channels = value.match(/\d+/g); if (!channels || channels.length < 3) return '#000000';
  return '#' + channels.slice(0, 3).map(number => Number(number).toString(16).padStart(2, '0')).join('');
}
function displayValue(prop) { return selectorRules()[prop] ?? selection?.computed?.[prop] ?? ''; }

function setProperty(prop, value, render = true) {
  if (!selection || value === undefined || value === '') return;
  const current = rules()[selection.selector] || {};
  rules()[selection.selector] = { ...current, [prop]: value };
  recordHistory(); if (render) renderControls(); applyOverrides(); updateChrome();
}
function resetProperty(prop = selectedProperty) {
  if (!selection || !prop || !(prop in selectorRules())) return;
  delete rules()[selection.selector][prop];
  if (!Object.keys(rules()[selection.selector]).length) delete rules()[selection.selector];
  recordHistory(); renderControls(); applyOverrides(); updateChrome();
}
function resetElement() {
  if (!selection || !rules()[selection.selector]) return;
  delete rules()[selection.selector]; recordHistory(); renderControls(); applyOverrides(); updateChrome();
}

function buildNumberControls() {
  document.querySelectorAll('.number-control').forEach(box => {
    const { prop, unit = '', step = '1', min, max, slider } = box.dataset;
    box.innerHTML = `<button type="button" data-delta="-1" title="Decrease">−</button><input data-prop="${prop}" type="number" step="${step}" ${min ? `min="${min}"` : ''} ${max ? `max="${max}"` : ''}><span class="unit">${unit}</span><button type="button" data-delta="1" title="Increase">+</button>${slider ? `<input class="range" data-prop="${prop}" type="range" step="${step}" min="${min || 0}" max="${max || 100}">` : ''}`;
    const input = box.querySelector('input[type=number]');
    input.addEventListener('focus', () => { selectedProperty = prop; updateChrome(); input.select(); });
    input.addEventListener('input', () => { if (input.value !== '') setProperty(prop, `${input.value}${unit}`, false); });
    input.addEventListener('change', () => setProperty(prop, `${input.value}${unit}`));
    input.addEventListener('keydown', event => { if (event.key === 'Escape') { input.blur(); } });
    box.querySelectorAll('button').forEach(button => button.addEventListener('click', () => { const base = numericValue(displayValue(prop)); const next = Number((base.value + Number(button.dataset.delta) * Number(step)).toFixed(4)); setProperty(prop, `${next}${unit || base.unit}`); }));
    const range = box.querySelector('.range'); if (range) range.addEventListener('input', () => setProperty(prop, `${range.value}${unit}`, false));
  });
}

function renderControls() {
  if (!selection) return;
  el.name.textContent = selection.label;
  el.selector.textContent = selection.selector;
  el.parent.disabled = false;
  el.empty.classList.add('hidden'); el.controls.classList.remove('hidden');
  el.textEditor.disabled = !selection.editable;
  el.textEditor.value = selection.editable ? (selection.text || '') : '';
  el.textEditorHint.classList.toggle('hidden', !!selection.editable);
  document.querySelectorAll('.number-control').forEach(box => {
    const prop = box.dataset.prop; const parsed = numericValue(displayValue(prop)); const input = box.querySelector('input[type=number]');
    input.value = Number.isFinite(parsed.value) ? parsed.value : '';
    const range = box.querySelector('.range'); if (range) range.value = Math.max(Number(range.min), Math.min(Number(range.max), parsed.value || 0));
  });
  document.querySelectorAll('select[data-prop], input[type=text][data-prop]').forEach(input => { const value = displayValue(input.dataset.prop); if (input.tagName === 'SELECT') { if ([...input.options].some(option => option.value === value)) input.value = value; } else input.value = value; });
  document.querySelectorAll('.color-control').forEach(control => { const prop = control.querySelector('input').dataset.prop; const value = displayValue(prop); control.querySelector('input[type=color]').value = rgbToHex(value); control.querySelector('.color-text').value = value; });
}

function chooseBreakpoint(name) {
  activeBreakpoint = name; const info = BREAKPOINTS[name];
  document.querySelectorAll('.mode-button').forEach(button => button.classList.toggle('active', button.dataset.breakpoint === name));
  el.viewport.className = `viewport-frame ${name}`; el.viewportLabel.textContent = `${info.width} px · ${info.label}`;
  renderControls(); updateChrome();
}

async function save() {
  const response = await fetch('/__vt__/api/state', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({state}) });
  const result = await response.json();
  if (!result.ok) throw new Error(result.error || 'Could not save');
  el.status.textContent = `Saved · ${result.css}`;
}
async function copyCss() {
  try { await navigator.clipboard.writeText(cssFromState()); el.status.textContent = 'CSS copied to clipboard'; }
  catch { el.status.textContent = 'Clipboard permission was not available — use Export CSS'; }
}

function wireStaticControls() {
  buildNumberControls();
  el.textEditor.addEventListener('input', () => { if (selection?.editable) postToFrame({ type:'content-op', op:{ op:'text', selector: selection.selector, text: el.textEditor.value } }); });
  el.textEditor.addEventListener('change', () => { if (selection?.editable) recordContentOp({ op:'text', selector: selection.selector, text: el.textEditor.value }); });
  el.duplicateBtn.addEventListener('click', duplicateElement);
  el.deleteBtn.addEventListener('click', deleteElement);
  document.querySelectorAll('.section-title').forEach(button => button.addEventListener('click', () => button.closest('.panel-section').classList.toggle('open')));
  document.querySelectorAll('select[data-prop], input[type=text][data-prop]').forEach(input => {
    input.addEventListener('focus', () => { selectedProperty = input.dataset.prop; updateChrome(); });
    input.addEventListener('change', () => setProperty(input.dataset.prop, input.value));
  });
  document.querySelectorAll('.color-control').forEach(control => {
    const color = control.querySelector('input[type=color]'), text = control.querySelector('.color-text');
    color.addEventListener('input', () => { text.value = color.value; setProperty('color', color.value); });
    text.addEventListener('focus', () => { selectedProperty = 'color'; updateChrome(); }); text.addEventListener('change', () => setProperty('color', text.value));
  });
  document.querySelectorAll('.mode-button').forEach(button => button.addEventListener('click', () => chooseBreakpoint(button.dataset.breakpoint)));
  el.compare.addEventListener('click', () => { state.enabled = !state.enabled; applyOverrides(); updateChrome(); });
  el.undo.addEventListener('click', () => restoreHistory(historyIndex - 1)); el.redo.addEventListener('click', () => restoreHistory(historyIndex + 1));
  el.resetProp.addEventListener('click', () => resetProperty()); el.resetElement.addEventListener('click', resetElement);
  el.parent.addEventListener('click', () => postToFrame({type:'select-parent'}));
  el.save.addEventListener('click', () => save().catch(error => el.status.textContent = `Save failed: ${error.message}`)); el.copy.addEventListener('click', copyCss);
  window.addEventListener('keydown', event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); restoreHistory(event.shiftKey ? historyIndex + 1 : historyIndex - 1); } });
}

window.addEventListener('message', async event => {
  if (event.origin !== window.location.origin || !event.data?.visualTuner) return;
  if (event.data.type === 'selected') { selection = event.data; selectedProperty = null; renderControls(); updateChrome(); }
  if (event.data.type === 'hover' && !selection) el.status.textContent = event.data.label;
  if (event.data.type === 'ready') {
    await stateReady; // the iframe can announce 'ready' before our own state fetch below resolves
    postToFrame({ type:'apply-content', ops: state.content }); applyOverrides(); if (selection) postToFrame({type:'select', selector:selection.selector});
  }
});

(async function init() {
  const response = await fetch('/__vt__/api/state'); const payload = await response.json(); state = payload.state;
  state.content = state.content || [];
  history = [{ rules: clone(state.rules), content: clone(state.content) }]; historyIndex = 0; wireStaticControls(); updateChrome();
  resolveStateReady();
})();
